# Generated by Django 3.1.2 on 2021-09-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210919_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_date',
        ),
    ]
