# Generated by Django 3.1.2 on 2021-09-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_publish_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
